name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Debug build output
        run: |
          ls -la dist
          ls -la demo
        
      - name: Prepare deployment
        run: |
          cp -r demo/* dist/ || true
          ls -la dist
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages

 # publish:
 #   needs: build
 #   runs-on: ubuntu-latest
 #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 #   steps:
 #     - uses: actions/checkout@v3
 #     
 #     - name: Setup Node.js
 #       uses: actions/setup-node@v3
 #       with:
 #         node-version: '18'
 #         registry-url: 'https://registry.npmjs.org'
 #         
 #     - name: Install dependencies
 #       run: npm ci
 #       
 #     - name: Build
 #       run: npm run build
 #       
  #    - name: Publish to npm
  #      run: npm publish --access public
  #      env:
  #        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 