name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Prepare deployment
        run: |
          # Clean docs directory
          rm -rf docs/*
          
          # Copy all necessary files
          cp dist/demo.js docs/
          cp static/index.html docs/
          cp static/styles.css docs/
          cp static/bulma.min.css docs/
          cp static/demo.css docs/
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          commit_message: "Deploy to GitHub Pages"
          force_orphan: true

 # publish:
 #   needs: build
 #   runs-on: ubuntu-latest
 #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
 #   steps:
 #     - uses: actions/checkout@v3
 #     
 #     - name: Setup Node.js
 #       uses: actions/setup-node@v3
 #       with:
 #         node-version: '18'
 #         registry-url: 'https://registry.npmjs.org'
 #         
 #     - name: Install dependencies
 #       run: npm ci
 #       
 #     - name: Build
 #       run: npm run build
 #       
  #    - name: Publish to npm
  #      run: npm publish --access public
  #      env:
  #        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }} 